version: "3.9"

networks:
  frontend:
    external: false
    name: frontend
  backend:
    external: false
    name: backend

volumes:
  mongo_store:

services:
  mongo_db:
    networks:
    - backend
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_store:/data
  api_service:
    networks:
      - backend
    build: backend/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  node:
    networks:
      - frontend
    build: frontend/
    restart: always
    ports: 
      - 4200:80
    depends_on:
      - api_service